# Generated by Django 5.1.4 on 2025-05-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0006_remove_photo_descripation_photo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='time',
        ),
        migrations.AddField(
            model_name='record',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='working_hours',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
