# Generated by Django 5.1.4 on 2025-05-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0009_company_employee_delete_logindata_delete_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
