# Generated by Django 5.1.4 on 2025-05-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0014_alter_employee_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_image/'),
        ),
    ]
