# Generated by Django 5.1.4 on 2025-05-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0016_alter_employee_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='company',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='smtp_port',
        ),
    ]
